services:
#  pgvector:
#    image: 'pgvector/pgvector:pg16'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    labels:
#      - "org.springframework.boot.service-connection=postgres"
#    ports:
#      - '5432'

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        limits:
          memory: 48g

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vector_store
      - PGPASSWORD=postgres  #Todo: supprimer cette ligne
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres","-d postgres" ]
      interval: 10s
      timeout: 20s
      retries: 10


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    configs:
      - source: pgadmin_config
        target: /pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy

configs:
  pgadmin_config:
    file: ./servers.json


